---
- name: Configure Nginx on both servers
  hosts: web
  become: true
  gather_facts: true
  vars:
    
    site_root: /web/html

  tasks:
    - name: Install nginx
      ansible.builtin.package:
        name: nginx
        state: present
        update_cache: true

    - name: Ensure site root directory exists (for index.html)
      ansible.builtin.file:
        path: "{{ site_root }}"
        state: directory
        mode: '0755'
        recurse: true

    - name: Copy nginx site config to sites-available/default
      ansible.builtin.copy:
        src: files/nginx.conf
        dest: /etc/nginx/sites-available/default
        owner: root
        group: root
        mode: '0644'

    - name: Link sites-enabled/default to sites-available/default
      ansible.builtin.file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link
        force: true

    - name: Render index.html from template
      ansible.builtin.template:
        src: templates/index.html.j2
        dest: "{{ site_root }}/index.html"
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Reload and enable nginx service
      ansible.builtin.service:
        name: nginx
        state: reloaded
        enabled: true
